Bot:
  prefix: .
  serverid: 123456789
  token: NzY5MDc0Nzk3MTIzNDY5MzQz.X5JuuA.ri4D_driVfoe3gDx8FqgYk9opTQ
Server:
  reactrolechannelid: 123456789
  logchannelid: 123456789
  channelpart: er-Tisch
  channelcategoryid: 123456789
  secondsuntilmove: 30
  ignoredchannels:
    - 2er-Tisch ðŸš«
    - 3er-Tisch ðŸš«
  finalchannelid: 123456789
  greetmsg: some join text (happy)
  leavemsg: some leave text (sad)
  joinroleid: 123456789
  reactrolemsgid: 123456789
Db:
  main: ./db/database.db